// Discovery cards: fun, true facts for each special interest.
// Each card: [emoji, short title, one fact]. Lists go from simplest to more advanced.
const DISCOVERIES={
 animals:[
  ['🐙','Octopus hearts','An octopus has three hearts and blue blood.'],
  ['🦘','Baby kangaroos','A baby kangaroo is called a joey, and it grows inside its mother\'s pouch.'],
  ['🐘','Handy trunks','An elephant uses its trunk to smell, breathe, drink, and pick things up.'],
  ['🦓','Zebra stripes','Every zebra has its own stripe pattern, a bit like a fingerprint.'],
  ['🐧','Swimming birds','Penguins are birds that cannot fly, but they are excellent swimmers.'],
  ['🐨','Sleepy koalas','Koalas can sleep up to about 20 hours a day.'],
  ['🦉','Owl heads','Owls can turn their heads about 270 degrees to look around.'],
  ['🦒','Giraffe tongues','A giraffe\'s tongue is dark purple and can be about 20 inches long.'],
  ['🐆','Speedy cheetahs','A cheetah can run up to about 70 miles per hour in short bursts.'],
  ['🦥','Slow sloths','Sloths move so slowly that tiny green algae can grow in their fur.'],
  ['🐪','Camel humps','A camel\'s hump stores fat, not water.'],
  ['🦩','Pink flamingos','Flamingos get their pink color from colorful pigments in the food they eat.']
 ],
 pets:[
  ['🐶','Super sniffers','A dog\'s sense of smell is thousands of times stronger than a person\'s.'],
  ['🐱','Happy purrs','Cats often purr when they feel happy and relaxed.'],
  ['🐹','Hamster cheeks','Hamsters carry food in stretchy pouches inside their cheeks.'],
  ['🐰','Growing teeth','A rabbit\'s front teeth never stop growing.'],
  ['🐈','Cat whiskers','Cats use their whiskers to sense things around them, even in the dark.'],
  ['🐕','Nose prints','Every dog has its own nose print, a bit like a human fingerprint.'],
  ['🐢','Turtle shells','A turtle\'s shell is part of its skeleton, so it can never climb out.'],
  ['🦜','Talking parrots','Some parrots can learn to copy dozens or even hundreds of words.'],
  ['🐟','Smart goldfish','Goldfish can learn tricks and remember things for months.'],
  ['🐾','Cooling off','Dogs sweat mostly through their paw pads and cool off by panting.'],
  ['😴','Cat naps','Cats usually sleep about 12 to 16 hours a day.'],
  ['🦎','Blinking geckos','Leopard geckos can blink because they have eyelids, unlike many other geckos.']
 ],
 farm:[
  ['🐷','Muddy pigs','Pigs roll in mud to stay cool because they cannot sweat very much.'],
  ['🥚','Egg colors','The color of a chicken egg depends on the breed of hen that laid it.'],
  ['🐔','Busy hens','A good laying hen can lay about 300 eggs in one year.'],
  ['🐑','Woolly coats','Most farm sheep need a haircut, called shearing, at least once a year.'],
  ['🐓','Crowing roosters','Roosters crow at many times of the day, not only at sunrise.'],
  ['🐴','Standing naps','Horses can doze while standing up by locking their legs in place.'],
  ['🦆','Waterproof ducks','Ducks spread a natural oil on their feathers to keep them waterproof.'],
  ['🐄','Cow stomachs','A cow\'s stomach has four parts that help it digest grass.'],
  ['🐐','Goat eyes','Goats have rectangle-shaped pupils that help them see a wide area around them.'],
  ['🌽','Corn rows','An ear of corn almost always has an even number of rows.'],
  ['🍄','Truffle hunters','Some pigs are trained to sniff out truffles, a special mushroom that grows underground.'],
  ['🐏','Face memory','Sheep can remember the faces of about 50 other sheep for up to 2 years.']
 ],
 ocean:[
  ['🐳','Biggest animal','The blue whale is the largest animal known to have ever lived.'],
  ['🦀','Sideways walk','Many crabs walk sideways.'],
  ['🐡','Puffy fish','A pufferfish can puff up into a ball by gulping lots of water.'],
  ['💧','Watery planet','Oceans cover about 71 percent of Earth\'s surface.'],
  ['🐠','Clownfish homes','Clownfish live safely among the stinging arms of sea anemones.'],
  ['🐬','Dolphin names','Each dolphin has its own special whistle that works a bit like a name.'],
  ['🐢','Coming home','Many sea turtles return to lay eggs on the same beach where they hatched.'],
  ['🦈','Shark teeth','Sharks keep growing new teeth all their lives and can go through thousands.'],
  ['⭐','Sea stars','Sea stars have no blood; they pump seawater through their bodies instead.'],
  ['🐋','Whale songs','Humpback whale songs can travel through the ocean for many miles.'],
  ['🦑','Giant eyes','Giant squid have eyes as big as dinner plates, among the largest of any animal.'],
  ['🌊','Deepest spot','The deepest part of the ocean, the Challenger Deep, is almost 7 miles deep.']
 ],
 dinos:[
  ['🥚','Dinosaur eggs','Baby dinosaurs hatched from eggs, just like baby birds do.'],
  ['🦖','Banana teeth','Tyrannosaurus rex had teeth about as long as bananas.'],
  ['🦕','Super long','Some long-necked dinosaurs grew longer than 2 school buses parked end to end.'],
  ['🦴','Stone bones','Scientists learn about dinosaurs by studying fossils, like bones that turned to stone.'],
  ['🦖','Tiny arms','Tyrannosaurus rex had short arms with only 2 fingers on each hand.'],
  ['🦕','Plates and spikes','Stegosaurus had big plates along its back and sharp spikes on its tail.'],
  ['🐦','Feathered dinosaurs','Many dinosaurs had feathers, even ones that could not fly.'],
  ['🐓','Living dinosaurs','Scientists say birds are living dinosaurs, even the chickens on a farm.'],
  ['📖','Terrible lizard','The word dinosaur comes from Greek words that mean terrible lizard.'],
  ['🌍','Every continent','Dinosaur fossils have been found on every continent, even Antarctica.'],
  ['🦅','Flying reptiles','Pterosaurs flew in the sky above dinosaurs, but they were not dinosaurs themselves.'],
  ['⏰','Time gap','Tyrannosaurus rex lived closer in time to us than to Stegosaurus.']
 ],
 bugs:[
  ['🐜','Strong ants','Some ants can carry things many times heavier than their own bodies.'],
  ['🦋','Tasty feet','Butterflies taste things with their feet.'],
  ['🐞','Ladybug spots','A ladybug\'s spots do not tell how old it is.'],
  ['🕷️','Count the legs','Spiders are not insects; spiders have 8 legs, and insects have 6.'],
  ['🐛','Big change','A caterpillar changes into a butterfly inside a chrysalis, or into a moth inside a cocoon.'],
  ['✨','Glowing fireflies','Fireflies make their own light using chemicals inside their bodies.'],
  ['🦗','Leg ears','Crickets have their ears on their front legs.'],
  ['🐝','Waggle dance','Honeybees do a waggle dance to show other bees where to find flowers.'],
  ['🍯','Tiny honey','A single honeybee makes only about one twelfth of a teaspoon of honey in its life.'],
  ['🏰','Huge colonies','Some ant colonies are home to millions of ants.'],
  ['🌎','Long journey','Monarch butterflies can fly up to about 3,000 miles to spend winter in Mexico.'],
  ['🕸️','Super silk','For its weight, spider silk is stronger than steel.']
 ],
 plants:[
  ['🌱','Plant food','Plants make their own food using sunlight, water, and air.'],
  ['🌵','Cactus water','A cactus stores water inside its thick stem.'],
  ['🌳','Tree rings','You can tell a tree\'s age by counting the rings inside its trunk.'],
  ['🌻','Sun followers','Young sunflowers turn to follow the Sun across the sky.'],
  ['🍃','Fresh oxygen','Plants give off oxygen, the gas that people and animals breathe.'],
  ['🍓','Outside seeds','A strawberry has about 200 seeds on the outside.'],
  ['🌼','Seed parachutes','Dandelion seeds float on tiny parachutes and can ride the wind for miles.'],
  ['🎋','Fast bamboo','Some kinds of bamboo can grow up to about 3 feet in one day.'],
  ['🌿','Snappy flytraps','A Venus flytrap snaps shut when tiny hairs inside it are touched twice.'],
  ['🍌','Berry surprise','Bananas are berries, but strawberries are not.'],
  ['🌲','Tallest trees','Coast redwoods are the tallest trees on Earth and can grow over 350 feet tall.'],
  ['🌴','Ancient seed','Scientists grew a date palm tree from a seed about 2,000 years old.']
 ],
 space:[
  ['☀️','Our star','The Sun is a star, and it is the closest star to Earth.'],
  ['🌕','Same face','The Moon always shows the same side to Earth.'],
  ['🔴','Red planet','Mars looks red because its dust and rocks contain lots of rusty iron.'],
  ['👣','Moon footprints','Footprints on the Moon could last millions of years because there is no wind.'],
  ['🌡️','Hottest planet','Venus is the hottest planet, even though Mercury is closer to the Sun.'],
  ['🪐','Giant Jupiter','Jupiter is so big that about 1,300 Earths could fit inside it.'],
  ['🛁','Floating Saturn','Saturn is less dense than water, so it could float in a giant enough bathtub.'],
  ['☄️','Comet tails','Comets are balls of ice and dust, and their tails point away from the Sun.'],
  ['💡','Sunlight trip','Light from the Sun takes about 8 minutes to reach Earth.'],
  ['🚀','Many sunrises','Astronauts on the International Space Station see about 16 sunrises every day.'],
  ['📏','Taller in space','Astronauts can grow up to about 2 inches taller in space because their spines stretch.'],
  ['⏳','Long Venus day','A day on Venus is longer than a whole year on Venus.']
 ],
 weather:[
  ['🌈','Rainbows','A rainbow forms when sunlight shines through raindrops and splits into colors.'],
  ['❄️','Snowflake shapes','Most snowflakes have 6 sides or 6 arms.'],
  ['🌫️','Ground clouds','Fog is a cloud that forms close to the ground.'],
  ['⛈️','Thunder sound','Thunder is the sound of air heated very quickly by lightning.'],
  ['☁️','Heavy clouds','A big puffy cloud can weigh about as much as 100 elephants.'],
  ['⚡','Hot lightning','A bolt of lightning is about 5 times hotter than the surface of the Sun.'],
  ['🌧️','Bun raindrops','Falling raindrops are shaped more like hamburger buns than teardrops.'],
  ['🧊','Growing hail','Hailstones grow bigger as winds toss them up and down inside a storm cloud.'],
  ['💧','Water cycle','The Sun\'s heat turns ocean water into vapor, which rises and forms clouds.'],
  ['🦗','Cricket thermometer','You can estimate the temperature by counting how often a cricket chirps.'],
  ['🌬️','Moving air','Wind is air moving from places with high pressure toward places with low pressure.'],
  ['🥶','Coldest place','The coldest temperature measured on Earth was about minus 128 degrees Fahrenheit, in Antarctica.']
 ],
 rocks:[
  ['💎','Hidden crystals','A geode can look like a plain rock outside but have sparkly crystals inside.'],
  ['🌋','New rock','When hot lava cools down, it hardens into new rock.'],
  ['🧂','Salty rock','Table salt is a mineral called halite.'],
  ['🌋','Floating rock','Pumice is a volcanic rock so full of air bubbles that it can float.'],
  ['💍','Hardest mineral','Diamond is the hardest natural mineral on Earth.'],
  ['✏️','Carbon cousins','Diamonds and the graphite in pencils are both made of carbon.'],
  ['🧲','Magnet rocks','Some rocks, like magnetite, are natural magnets.'],
  ['⛰️','Growing mountain','Mount Everest is still growing a tiny bit taller each year.'],
  ['🟠','Amber windows','Amber is hardened tree resin that can hold tiny insects from millions of years ago.'],
  ['🏜️','Carved canyon','The Colorado River carved the Grand Canyon over millions of years.'],
  ['🔍','Three rock types','Rocks come in 3 main types: igneous, sedimentary, and metamorphic.'],
  ['🔥','Hot core','Earth\'s inner core is about as hot as the surface of the Sun.']
 ],
 cars:[
  ['🚗','Horseless carriages','The first cars were called horseless carriages.'],
  ['🔌','Electric cars','Electric cars run on big batteries instead of gasoline.'],
  ['🚌','Yellow buses','School buses are painted a special yellow because it is easy to see.'],
  ['🚒','Tall ladders','Some fire trucks carry ladders that can reach over 100 feet high.'],
  ['🏎️','Race cars','Formula 1 race cars can go faster than 200 miles per hour.'],
  ['🚚','Monster tires','Monster truck tires are about 66 inches tall, taller than most kids.'],
  ['🚦','Traffic lights','The first traffic lights had only red and green, and yellow was added later.'],
  ['🛣️','Side of the road','Cars drive on the right in the United States but on the left in the United Kingdom.'],
  ['🏭','Assembly line','In 1913, Henry Ford began building Model T cars on a moving assembly line.'],
  ['🔋','Braking power','Many electric cars recharge their batteries a little when they slow down.'],
  ['⚙️','Busy pistons','In a gasoline engine, pistons move up and down thousands of times each minute.'],
  ['🏁','Faster than sound','In 1997, a car called Thrust SSC drove faster than the speed of sound.']
 ],
 trains:[
  ['🎈','Hot air balloons','Hot air balloons float because hot air is lighter than the cooler air around it.'],
  ['🚂','Steam trains','Steam trains burn coal or wood to boil water, and the steam makes the wheels turn.'],
  ['🚁','Hovering helicopters','Helicopters can fly straight up, hover in one place, and even fly backward.'],
  ['✈️','High fliers','Big passenger jets often fly about 6 or 7 miles above the ground.'],
  ['🛩️','First flight','In 1903, the Wright brothers\' first airplane flight lasted about 12 seconds.'],
  ['🚄','Bullet trains','Japan\'s bullet trains can travel at nearly 200 miles per hour.'],
  ['🚢','Giant ships','Some cargo ships are longer than 3 football fields.'],
  ['🚝','Floating trains','Maglev trains float just above the track using powerful magnets.'],
  ['⚓','Diving submarines','Submarines sink by filling special tanks with water and rise by filling them with air.'],
  ['⛵','Zigzag sailing','Sailboats can travel toward the wind by sailing in a zigzag path.'],
  ['🛫','Double-decker jet','The Airbus A380 is a double-decker jet that can carry up to about 850 passengers.'],
  ['🚆','Longest railway','The Trans-Siberian Railway in Russia is more than 5,700 miles long.']
 ],
 robots:[
  ['🧹','Robot vacuums','Robot vacuums use sensors to avoid bumping into walls and rolling down stairs.'],
  ['⚙️','Gears','Gears are wheels with teeth that fit together to pass motion along.'],
  ['🔧','Simple machines','Ramps, levers, and wheels are simple machines that make work easier.'],
  ['🏭','Factory robots','Robot arms help build cars in factories by welding and painting parts.'],
  ['🤖','Robot word','The word robot comes from a Czech word that means hard, forced work.'],
  ['📷','Robot senses','Robots use sensors like cameras and microphones to learn about the world around them.'],
  ['💻','Room-sized computers','Some of the first computers were so big they filled a whole room.'],
  ['🚙','Mars rover','NASA\'s Perseverance rover is a car-sized robot that landed on Mars in 2021.'],
  ['🌊','Ocean explorers','Scientists use underwater robots to explore the deepest parts of the ocean.'],
  ['🚁','Mars helicopter','In 2021, a small robot helicopter named Ingenuity became the first to fly on Mars.'],
  ['🎭','Ancient machines','About 2,000 years ago, an inventor named Hero built machines that moved by themselves.'],
  ['🛰️','Farthest traveler','The Voyager 1 space probe, launched in 1977, is the farthest human-made object from Earth.']
 ],
 sports:[
  ['⚽','Soccer fans','Soccer is the most popular sport in the whole world.'],
  ['🏀','Peach baskets','The very first basketball games used peach baskets as hoops.'],
  ['⛳','Dimpled balls','Golf balls have dimples that help them fly farther.'],
  ['🏒','Frozen pucks','Hockey pucks are frozen before games so they bounce less on the ice.'],
  ['🏈','Not a pig','A football is nicknamed a pigskin, but it is usually made of cowhide leather.'],
  ['⚾','Baseball stitches','A baseball has 108 double stitches holding its cover together.'],
  ['🎾','Yellow tennis balls','Tennis balls became yellow in 1972 so people could see them better on TV.'],
  ['🏃','Marathon miles','A marathon race is 26.2 miles long.'],
  ['🥇','Gold medals','Olympic gold medals are mostly silver with a coating of gold.'],
  ['🏊','Giant pools','An Olympic swimming pool holds about 660,000 gallons of water.'],
  ['🏐','Volleyball start','Volleyball was invented in 1895 in Massachusetts.'],
  ['🏛️','Ancient Olympics','The ancient Olympic Games began in Greece about 2,800 years ago.']
 ],
 music:[
  ['🎹','Piano keys','Most pianos have 88 keys.'],
  ['🎸','Guitar strings','Most guitars have 6 strings.'],
  ['🥁','Shaking drums','When you hit a drum, its top vibrates and shakes the air, making sound.'],
  ['🎻','Horsehair bows','A violin bow is usually strung with hair from a horse\'s tail.'],
  ['🎺','Trumpet valves','Trumpet players change notes using 3 valves and the shape of their lips.'],
  ['🎼','Big orchestras','A large orchestra can have about 100 musicians playing together.'],
  ['🎵','Harp strings','A large concert harp has 47 strings.'],
  ['🎶','Young Mozart','Mozart began writing his own music when he was about 5 years old.'],
  ['🎷','Surprise woodwind','The saxophone is made of brass but is a woodwind because it uses a reed.'],
  ['👂','Beethoven','Beethoven kept writing great music even after he lost almost all his hearing.'],
  ['🔊','Fast sound','Sound travels about 4 times faster through water than through air.'],
  ['🏛️','Giant organ','The largest pipe organ, in Atlantic City, New Jersey, has more than 33,000 pipes.']
 ],
 art:[
  ['🎨','Mixing colors','Mixing blue and yellow paint makes green.'],
  ['🖍️','First crayons','Crayola crayons first went on sale in 1903, with 8 colors in a box.'],
  ['🍞','Bread erasers','Before rubber erasers, people used bread crumbs to rub out pencil marks.'],
  ['🌈','Color wheel','Colors across from each other on the color wheel are called complementary colors.'],
  ['🖼️','Small Mona Lisa','The Mona Lisa is only about 30 inches tall.'],
  ['🌻','Sunflower paintings','Vincent van Gogh painted a famous series of pictures of sunflowers in vases.'],
  ['🗽','Green statue','The Statue of Liberty is green because its copper skin changed color over time.'],
  ['🐎','Cave art','People painted animals on cave walls more than 30,000 years ago.'],
  ['🗿','Hidden bodies','Some of the giant stone heads on Easter Island have bodies buried underground.'],
  ['🟡','Dot paintings','Georges Seurat made paintings out of thousands of tiny dots of color.'],
  ['⛪','Painted ceiling','Michelangelo spent about 4 years painting the ceiling of the Sistine Chapel.'],
  ['🔵','Precious blue','A blue paint called ultramarine was made from a stone and once cost more than gold.']
 ],
 food:[
  ['🍿','Popping corn','Popcorn pops because water inside each kernel turns into steam.'],
  ['🍎','Floating apples','Apples float in water because about one quarter of an apple is air.'],
  ['🍞','Rising bread','Bread rises because tiny living yeast makes bubbles of gas in the dough.'],
  ['🍫','Chocolate seeds','Chocolate is made from the seeds of the cacao tree.'],
  ['🍅','Tomato fruit','Tomatoes are fruits because they grow from flowers and hold seeds.'],
  ['🥕','Purple carrots','The first farmed carrots were mostly purple or yellow, not orange.'],
  ['🥜','Not a nut','Peanuts are not really nuts; they are legumes, like beans and peas.'],
  ['🍳','Egg magic','Cooking an egg changes its proteins, so the clear part turns white.'],
  ['🧀','Holey cheese','The holes in Swiss cheese come from gas bubbles made by tiny bacteria.'],
  ['🍦','Salty ice','Ice mixed with salt gets colder than plain ice, which helps freeze homemade ice cream.'],
  ['🌶️','Spicy peppers','The hot feeling from chili peppers comes from a chemical called capsaicin.'],
  ['🍯','Long-lasting honey','Sealed honey can stay good to eat for a very long time, even thousands of years.']
 ]
};
