// Expert words: one real above-grade word per Discovery card, in the same order as DISCOVERIES.
// Each word: [word, how to say it, meaning, band (m middle school, h high school, c college), question, [3 choices], answer index].
// jobs: real job titles earned at 3, 6 and 12 expert stamps in that interest.
const EXPERT={
 animals:{jobs:["Junior Zoologist", "Zoologist", "Chief Zoologist"],words:[
  ["cephalopod", "SEF-uh-luh-pod", "An ocean animal with arms on its head, like an octopus or squid.", "h", "Which animal is a cephalopod?", ["Squid", "Jellyfish", "Starfish"], 0],
  ["marsupial", "mar-SOO-pee-ul", "A mammal whose babies grow in a pouch, like a kangaroo.", "m", "Which animal is a marsupial?", ["Zebra", "Owl", "Koala"], 2],
  ["proboscis", "proh-BOS-kis", "A long, bendy nose or snout, like an elephant's trunk.", "h", "Which is an example of a proboscis?", ["An elephant's trunk", "A turtle's shell", "A bird's wing"], 0],
  ["pelage", "PEL-ij", "The fur or hair coat of a mammal, like a zebra's striped coat.", "c", "What is a zebra's pelage?", ["Its hooves", "Its fur coat", "Its tail"], 1],
  ["hydrodynamic", "HY-droh-dy-NAM-ik", "Shaped to slide easily through water, like a penguin's smooth body.", "h", "Which shape is the most hydrodynamic?", ["Flat and square", "Bumpy and round", "Smooth and pointed"], 2],
  ["folivore", "FOH-lih-vor", "An animal that eats mostly leaves, like a koala eating eucalyptus.", "c", "What does a folivore mostly eat?", ["Leaves", "Fish", "Insects"], 0],
  ["vertebrae", "VER-tuh-bray", "The small bones that make up the backbone. Owls have 14 in their necks.", "m", "Where would you find vertebrae?", ["In the eye", "In the backbone", "In a feather"], 1],
  ["prehensile", "pree-HEN-sul", "Able to grab and hold things, like a giraffe's long tongue.", "h", "What can a prehensile tongue do?", ["Grab leaves", "Change color", "Make music"], 0],
  ["fast-twitch muscle", "FAST-twich MUS-ul", "Muscle that gives quick, strong bursts of speed, like a cheetah's sprint.", "h", "What is fast-twitch muscle best for?", ["Long, slow walks", "Quick bursts of speed", "Sleeping"], 1],
  ["symbiosis", "sim-bee-OH-sis", "Two different living things living closely together, like a sloth and algae.", "m", "Which is an example of symbiosis?", ["A rock rolling", "Rain falling", "Algae in sloth fur"], 2],
  ["adipose tissue", "AD-ih-pohs TISH-oo", "Body tissue that stores fat, like the fat in a camel's hump.", "h", "What does adipose tissue store?", ["Water", "Fat", "Air"], 1],
  ["carotenoids", "kuh-ROT-uh-noydz", "Orange and red pigments in food that turn flamingos pink.", "h", "Which food is full of carotenoids?", ["Carrots", "Rice", "Milk"], 0]
 ]},
 pets:{jobs:["Veterinary Assistant", "Veterinarian", "Chief Veterinarian"],words:[
  ["olfactory", "ol-FAK-tuh-ree", "Having to do with the sense of smell, which is super strong in dogs.", "h", "Which sense is olfactory?", ["Hearing", "Smell", "Taste"], 1],
  ["larynx", "LAIR-inks", "The voice box in the throat. Cats purr using muscles in it.", "m", "Where is the larynx?", ["In the throat", "In the paw", "In the tail"], 0],
  ["buccal pouch", "BUK-ul powch", "A stretchy pocket inside the cheek where a hamster carries food.", "c", "What does a hamster carry in its buccal pouches?", ["Pebbles", "Water", "Food"], 2],
  ["elodont", "EL-oh-dont", "Teeth that keep growing all life long, like a rabbit's front teeth.", "c", "Which animal has elodont teeth?", ["Person", "Rabbit", "Cat"], 1],
  ["vibrissae", "vy-BRIS-ee", "Stiff, sensitive whiskers that feel air movements and nearby objects.", "c", "What are a cat's vibrissae?", ["Its claws", "Its ears", "Its whiskers"], 2],
  ["biometrics", "by-oh-MET-riks", "Using body features, like fingerprints or nose prints, to tell who is who.", "h", "Which is a kind of biometrics?", ["A fingerprint scan", "A name tag", "A collar"], 0],
  ["carapace", "KAIR-uh-pays", "The top part of a turtle's shell, joined to its backbone and ribs.", "h", "Where is a turtle's carapace?", ["On its belly", "On its back", "On its feet"], 1],
  ["vocal mimicry", "VOH-kul MIM-ih-kree", "Copying sounds made by others, like a parrot copying words.", "h", "Which is an example of vocal mimicry?", ["A parrot saying hello", "A dog wagging its tail", "A cat napping"], 0],
  ["conditioning", "kun-DISH-uh-ning", "Learning by linking an action with a reward, like a fish learning tricks for food.", "h", "Which is an example of conditioning?", ["Fish grows bigger", "Fish changes color", "Fish learns tap means food"], 2],
  ["thermoregulation", "THER-moh-reg-yuh-LAY-shun", "How an animal keeps its body at the right temperature, like a dog panting.", "h", "What does thermoregulation control?", ["Hunger", "Body temperature", "Eyesight"], 1],
  ["crepuscular", "krih-PUS-kyuh-lur", "Most active at dawn and dusk, like many cats.", "c", "When is a crepuscular animal most active?", ["Dawn and dusk", "Noon", "Midnight only"], 0],
  ["brille", "BRIL", "A clear scale that covers the eye of geckos with no eyelids. Leopard geckos have eyelids instead.", "c", "What does a brille do?", ["Helps it climb", "Changes its color", "Protects the eye"], 2]
 ]},
 farm:{jobs:["Junior Farmhand", "Farm Manager", "Agricultural Scientist"],words:[
  ["evaporative cooling", "ee-VAP-uh-ruh-tiv KOO-ling", "Cooling down as water dries off the skin, like wet mud on a pig.", "h", "What causes evaporative cooling?", ["Eating cold food", "Water drying off skin", "Standing in the sun"], 1],
  ["biliverdin", "bil-ih-VER-din", "A natural pigment that colors the eggs of some hen breeds blue or green.", "c", "What color does biliverdin give eggs?", ["Pink", "Black", "Blue or green"], 2],
  ["oviduct", "OH-vih-dukt", "The tube inside a hen where an egg gets its white and shell.", "h", "Where does a hen's egg get its shell?", ["In the oviduct", "In the beak", "In the crop"], 0],
  ["lanolin", "LAN-uh-lin", "A natural waxy grease in sheep's wool, used in creams and lotions.", "h", "Where does lanolin come from?", ["Cow's milk", "Sheep's wool", "Corn plants"], 1],
  ["circadian rhythm", "ser-KAY-dee-un RITH-um", "The body's inner 24-hour clock, which helps roosters know when to crow.", "h", "About how long is one circadian rhythm cycle?", ["About 1 hour", "About 1 year", "About 24 hours"], 2],
  ["stay apparatus", "STAY ap-uh-RAT-us", "Special leg parts that lock so a horse can doze standing up.", "c", "What does a horse's stay apparatus let it do?", ["Doze standing up", "Run backward", "Jump higher"], 0],
  ["uropygial gland", "yur-oh-PIJ-ee-ul gland", "A gland near a bird's tail that makes oil for waterproof feathers.", "c", "What does the uropygial gland make?", ["Eggs", "Feather oil", "Quacking sounds"], 1],
  ["ruminant", "ROO-mih-nunt", "An animal with a four-part stomach that chews its cud, like a cow.", "h", "Which animal is a ruminant?", ["Pig", "Chicken", "Goat"], 2],
  ["peripheral vision", "puh-RIF-er-ul VIZH-un", "Seeing things off to the sides while looking straight ahead, like a goat.", "m", "What does peripheral vision help you see?", ["Things off to the side", "Tiny germs", "Faraway planets"], 0],
  ["spikelet", "SPYK-lit", "A tiny flower cluster. On corn they grow in pairs, making even rows.", "c", "On an ear of corn, spikelets grow in what?", ["Threes", "Pairs", "Fives"], 1],
  ["mycology", "my-KOL-uh-jee", "The science of mushrooms and other fungi, like truffles.", "h", "What does mycology study?", ["Rocks", "Pigs", "Mushrooms and fungi"], 2],
  ["facial recognition", "FAY-shul rek-ug-NISH-un", "Knowing who someone is by their face, like sheep remembering other sheep.", "h", "What does facial recognition use to identify someone?", ["Their face", "Their voice", "Their smell"], 0]
 ]},
 ocean:{jobs:["Junior Marine Biologist", "Marine Biologist", "Chief Marine Biologist"],words:[
  ["cetacean", "sih-TAY-shun", "A whale, dolphin, or porpoise, like the giant blue whale.", "h", "Which animal is a cetacean?", ["Dolphin", "Shark", "Seal"], 0],
  ["crustacean", "krus-TAY-shun", "An animal with a hard outer shell and jointed legs, like a crab.", "m", "Which animal is a crustacean?", ["Octopus", "Lobster", "Jellyfish"], 1],
  ["defense mechanism", "dih-FENS MEK-uh-niz-um", "A way an animal protects itself, like a pufferfish puffing up.", "h", "Which is a defense mechanism?", ["A fish eating lunch", "A fish resting", "A pufferfish puffing up"], 2],
  ["hydrosphere", "HY-druh-sfeer", "All the water on Earth, including oceans, lakes, rivers, and ice.", "m", "Which is part of the hydrosphere?", ["An ocean", "A mountain", "The Moon"], 0],
  ["mutualism", "MYOO-choo-uh-liz-um", "When two living things help each other, like clownfish and sea anemones.", "h", "In mutualism, who gets helped?", ["Only one partner", "Both partners", "Neither partner"], 1],
  ["signature whistle", "SIG-nuh-cher WIS-ul", "A dolphin's own special whistle that works like its name.", "c", "What does a dolphin's signature whistle work like?", ["A map", "A clock", "A name"], 2],
  ["natal homing", "NAY-tul HOH-ming", "Returning to the place where you were born, like sea turtles laying eggs.", "c", "Where does natal homing lead a sea turtle?", ["Its birth beach", "A frozen lake", "A coral cave"], 0],
  ["polyphyodont", "pol-ee-FY-oh-dont", "An animal that keeps replacing its teeth all its life, like a shark.", "c", "What does a polyphyodont animal keep doing?", ["Changing color", "Replacing its teeth", "Growing new fins"], 1],
  ["water vascular system", "WAH-ter VAS-kyuh-ler SIS-tum", "Tubes that move seawater through a sea star's body to help it move.", "h", "What flows through a sea star's water vascular system?", ["Blood", "Air", "Seawater"], 2],
  ["hydrophone", "HY-druh-fohn", "An underwater microphone scientists use to listen to whale songs.", "h", "What is a hydrophone used for?", ["Listening underwater", "Seeing in the dark", "Measuring waves"], 0],
  ["deep-sea gigantism", "DEEP-see jy-GAN-tiz-um", "When deep-sea animals, like giant squid, grow much bigger than their relatives.", "c", "Where does deep-sea gigantism happen?", ["In deserts", "In the deep ocean", "In treetops"], 1],
  ["hadal zone", "HAY-dul zohn", "The deepest part of the ocean, in trenches like the Challenger Deep.", "c", "Where is the hadal zone?", ["Sandy beaches", "Coral reefs", "Deep ocean trenches"], 2]
 ]},
 dinos:{jobs:["Junior Paleontologist", "Paleontologist", "Chief Paleontologist"],words:[
  ["oviparous", "oh-VIP-er-us", "Laying eggs that hatch outside the body, like dinosaurs and birds.", "h", "Which animal is oviparous?", ["Chicken", "Dog", "Horse"], 0],
  ["serrated", "SAIR-ay-tid", "Having a jagged edge like a saw, like T. rex teeth.", "m", "Which tool has a serrated edge?", ["A spoon", "A bread knife", "A pencil"], 1],
  ["sauropod", "SOR-uh-pod", "A giant plant-eating dinosaur with a long neck and long tail.", "h", "Which dinosaur was a sauropod?", ["Triceratops", "Velociraptor", "Brachiosaurus"], 2],
  ["permineralization", "per-MIN-er-ul-ih-ZAY-shun", "When minerals fill tiny spaces in bones and slowly turn them to stone.", "c", "What fills the bones during permineralization?", ["Minerals", "Air bubbles", "Plant roots"], 0],
  ["forelimb", "FOR-lim", "A front leg or arm, like the short arms of T. rex.", "m", "Which is a forelimb?", ["A dog's tail", "A bird's wing", "A cat's ear"], 1],
  ["osteoderm", "OS-tee-oh-durm", "A bony plate or spike that grows in the skin, like Stegosaurus's back plates and tail spikes.", "c", "Where does an osteoderm grow?", ["In the stomach", "In the brain", "In the skin"], 2],
  ["protofeathers", "PROH-toh-feth-erz", "Simple, fuzzy early feathers found on many dinosaur fossils.", "c", "What did protofeathers look like?", ["Simple fuzzy fibers", "Hard scales", "Shiny shells"], 0],
  ["theropod", "THEER-uh-pod", "A group of two-legged dinosaurs that includes T. rex and today's birds.", "h", "Which animal is a living theropod?", ["A lizard", "A robin", "A crocodile"], 1],
  ["etymology", "et-ih-MOL-uh-jee", "The story of where a word comes from, like dinosaur from Greek.", "h", "What does etymology study?", ["Old bones", "Rock layers", "Where words come from"], 2],
  ["Pangaea", "pan-JEE-uh", "The giant supercontinent that joined all land when the first dinosaurs lived.", "m", "What was Pangaea?", ["A giant supercontinent", "A kind of dinosaur", "An ocean"], 0],
  ["patagium", "puh-TAY-jee-um", "A thin wing made of skin, like the wings pterosaurs used to fly.", "c", "What is a patagium made of?", ["Feathers", "Skin", "Scales"], 1],
  ["Mesozoic Era", "mez-uh-ZOH-ik EER-uh", "The age of dinosaurs, which lasted about 186 million years.", "h", "What is the Mesozoic Era known as?", ["The Ice Age", "The Stone Age", "The age of dinosaurs"], 2]
 ]},
 bugs:{jobs:["Junior Entomologist", "Entomologist", "Chief Entomologist"],words:[
  ["exoskeleton", "EK-soh-SKEL-uh-tun", "A hard outer shell that supports and protects a bug's body, like an ant's.", "m", "Where is an insect's exoskeleton?", ["On the outside", "Deep inside", "In its brain"], 0],
  ["chemoreceptor", "KEE-moh-rih-SEP-ter", "A body part that senses chemicals, like the tasters on a butterfly's feet.", "c", "What does a chemoreceptor sense?", ["Light", "Chemicals, like tastes", "Loud sounds"], 1],
  ["aposematism", "ap-oh-SEM-uh-tiz-um", "Bright warning colors, like a ladybug's red and black, that say I taste bad.", "c", "What do aposematic colors tell predators?", ["I am sleepy", "I am lost", "I taste bad"], 2],
  ["arachnid", "uh-RAK-nid", "An 8-legged animal like a spider or scorpion. It is not an insect.", "m", "Which animal is an arachnid?", ["Tick", "Beetle", "Ant"], 0],
  ["complete metamorphosis", "kum-PLEET met-uh-MOR-fuh-sis", "A life cycle with 4 stages: egg, larva, pupa, and adult, like caterpillar to butterfly.", "m", "Which insect goes through complete metamorphosis?", ["Grasshopper", "Butterfly", "Cockroach"], 1],
  ["bioluminescence", "by-oh-loo-mih-NES-ens", "Light made by a living thing, like a firefly's glow.", "h", "Which animal uses bioluminescence?", ["Robin", "Cow", "Anglerfish"], 2],
  ["tympanum", "TIM-puh-num", "A thin eardrum. Crickets have one on each front leg.", "c", "What does a cricket's tympanum help it do?", ["Hear", "Fly", "Eat"], 0],
  ["ethology", "ee-THOL-uh-jee", "The science of how animals act, like bees dancing to share directions.", "c", "What does ethology study?", ["Weather", "Animal behavior", "Rocks"], 1],
  ["apiculture", "AY-pih-kul-cher", "Caring for honeybees to collect their honey. It is also called beekeeping.", "c", "What is apiculture?", ["Bird watching", "Fishing", "Beekeeping"], 2],
  ["eusocial", "yoo-SOH-shul", "Living in big teams with workers and a queen who lays the eggs, like ants.", "c", "Which insect is eusocial?", ["Honeybee", "Butterfly", "Grasshopper"], 0],
  ["overwintering", "OH-ver-WIN-ter-ing", "Spending the winter in a safe place, like monarchs in Mexico.", "h", "Where do many monarchs go for overwintering?", ["Canada", "Mexico", "Alaska"], 1],
  ["tensile strength", "TEN-sul strength", "How hard you can pull something before it breaks, like spider silk.", "h", "What does tensile strength measure?", ["How heavy it is", "Its color", "Pulling before it breaks"], 2]
 ]},
 plants:{jobs:["Junior Botanist", "Botanist", "Chief Botanist"],words:[
  ["photosynthesis", "foh-toh-SIN-thuh-sis", "How plants use sunlight, water, and air to make their own food.", "m", "What does photosynthesis help a plant make?", ["Its own food", "Loud sounds", "Colorful rocks"], 0],
  ["succulent", "SUK-yoo-lent", "A plant with thick parts that store water, like a cactus.", "m", "What does a succulent store in its thick parts?", ["Sand", "Water", "Honey"], 1],
  ["dendrochronology", "den-droh-kruh-NOL-uh-jee", "Finding a tree's age and past weather by studying its rings.", "c", "What do experts study in dendrochronology?", ["Ocean waves", "Bird songs", "Tree rings"], 2],
  ["heliotropism", "hee-lee-OT-ruh-piz-um", "When a plant turns to follow the Sun across the sky.", "h", "A plant showing heliotropism turns to follow what?", ["The Sun", "The Moon", "The rain"], 0],
  ["stomata", "STOH-muh-tuh", "Tiny holes in leaves that let oxygen out and carbon dioxide in.", "m", "Where are a plant's stomata?", ["Deep in the soil", "On its leaves", "Inside its seeds"], 1],
  ["achene", "uh-KEEN", "A tiny dry fruit holding one seed, like the dots on a strawberry.", "c", "What are the little dots on a strawberry called?", ["Petals", "Thorns", "Achenes"], 2],
  ["seed dispersal", "seed dis-PUR-sul", "How seeds travel away from the parent plant, like riding the wind.", "m", "What is seed dispersal?", ["Seeds spreading to new places", "Seeds turning into rocks", "Seeds changing color"], 0],
  ["meristem", "MAIR-ih-stem", "The part of a plant where new cells are made so it grows.", "h", "What happens in a plant's meristem?", ["Water freezes", "New cells grow", "Seeds get eaten"], 1],
  ["thigmonasty", "THIG-moh-nas-tee", "A plant moving because it was touched, like a flytrap snapping shut.", "c", "What makes a plant move in thigmonasty?", ["Loud music", "Cold snow", "Being touched"], 2],
  ["pericarp", "PAIR-ih-karp", "The wall of a fruit around its seeds, like a banana's peel and soft insides.", "c", "What part of a fruit is the pericarp?", ["The fruit wall", "The roots", "The flower smell"], 0],
  ["xylem", "ZY-lum", "Tiny tubes that carry water up from the roots, even to redwood treetops.", "m", "What does xylem carry up a tree?", ["Sunlight", "Water", "Birds"], 1],
  ["dormancy", "DOR-mun-see", "A resting time when a living seed waits before it sprouts.", "m", "A seed in dormancy is doing what?", ["Growing tall fast", "Making flowers", "Resting until it sprouts"], 2]
 ]},
 space:{jobs:["Junior Astronomer", "Astronomer", "Chief Astronomer"],words:[
  ["nuclear fusion", "NOO-klee-er FYOO-zhun", "When tiny atoms squeeze together and release energy, making the Sun shine.", "h", "What does nuclear fusion make the Sun do?", ["Shine", "Spin backward", "Turn blue"], 0],
  ["tidal locking", "TY-dul LOK-ing", "When a moon spins once per orbit, so one side always faces its planet.", "h", "Because of tidal locking, what do we see of the Moon?", ["Only its far side", "Always the same side", "A new side daily"], 1],
  ["iron oxide", "EYE-urn OK-side", "The chemical name for rust, which makes Mars look red.", "m", "What is another name for iron oxide?", ["Ice", "Salt", "Rust"], 2],
  ["regolith", "REG-uh-lith", "The loose dust and broken rock covering the Moon's surface.", "h", "What is regolith?", ["Loose dust and rock", "Moon water", "A space rocket"], 0],
  ["greenhouse effect", "GREEN-hows ih-FEKT", "When gases trap heat like a blanket, making Venus super hot.", "m", "What does the greenhouse effect do?", ["Makes planets float", "Traps heat", "Creates rings"], 1],
  ["gas giant", "gas JY-unt", "A huge planet made mostly of gas, like Jupiter.", "m", "What is a gas giant mostly made of?", ["Solid rock", "Liquid water", "Gas"], 2],
  ["density", "DEN-sih-tee", "How much stuff is packed into a space; Saturn has very low density.", "m", "Something with low density, like Saturn, could do what in water?", ["Float", "Sink fast", "Melt"], 0],
  ["solar wind", "SOH-ler wind", "A stream of tiny particles from the Sun that helps push comet tails away from it.", "m", "Which way does solar wind push a comet's tail?", ["Toward the Sun", "Away from the Sun", "In a circle"], 1],
  ["astronomical unit", "as-truh-NOM-ih-kul YOO-nit", "The average distance from Earth to the Sun, about 93 million miles.", "h", "What does one astronomical unit measure?", ["A planet's weight", "How hot stars are", "Earth-to-Sun distance"], 2],
  ["orbital period", "OR-bih-tul PEER-ee-ud", "How long it takes to go around once; the space station takes about 90 minutes.", "h", "What is an orbital period?", ["A rocket's fuel tank", "Time for one trip around", "A space helmet"], 1],
  ["microgravity", "MY-kroh-grav-ih-tee", "The floaty feeling in space where people and things seem almost weightless.", "h", "What does microgravity make astronauts feel?", ["Almost weightless", "Very heavy", "Very cold"], 0],
  ["retrograde rotation", "RET-ruh-grayd roh-TAY-shun", "Spinning backward compared to most planets; Venus spins slowly this way.", "h", "What does retrograde rotation mean?", ["Spinning super fast", "Not spinning at all", "Spinning backward"], 2]
 ]},
 weather:{jobs:["Junior Meteorologist", "Meteorologist", "Chief Meteorologist"],words:[
  ["refraction", "rih-FRAK-shun", "When light bends as it passes into something, like a raindrop.", "m", "What happens to light during refraction?", ["It freezes", "It bends", "It gets louder"], 1],
  ["dendrite", "DEN-dryt", "A branching, tree-like crystal, like a snowflake with 6 feathery arms.", "h", "What does a dendrite snowflake look like?", ["Branching like a tree", "A smooth round ball", "A flat square"], 0],
  ["dew point", "DOO poynt", "The temperature where air is cool enough for its water vapor to turn into tiny droplets, making fog or dew.", "h", "What forms when air cools to its dew point?", ["Rainbows", "Sand", "Tiny water droplets"], 2],
  ["shock wave", "SHOK wayv", "A strong burst of pressure racing through air; lightning's shock wave makes thunder.", "h", "What sound does lightning's shock wave make?", ["Thunder", "A whistle", "A buzz"], 0],
  ["cumulus", "KYOO-myuh-lus", "A big, puffy cloud that looks like cotton.", "m", "What does a cumulus cloud look like?", ["Thin and wispy", "Big and puffy", "Flat and gray"], 1],
  ["plasma", "PLAZ-muh", "Super hot, glowing gas; a lightning bolt is made of plasma.", "h", "What is plasma?", ["Frozen rain", "Soft mud", "Super hot glowing gas"], 2],
  ["surface tension", "SUR-fis TEN-shun", "Water's stretchy, skin-like pull that holds a raindrop together.", "m", "What does surface tension do to a raindrop?", ["Holds it together", "Makes it hot", "Turns it green"], 0],
  ["updraft", "UP-draft", "Rising air inside a storm cloud that pushes hailstones back up.", "m", "Which way does an updraft move air?", ["Down", "Up", "Only sideways"], 1],
  ["hydrologic cycle", "hy-druh-LOJ-ik SY-kul", "The science name for the water cycle: water turns to vapor, forms clouds, and falls as rain or snow.", "h", "What is the hydrologic cycle?", ["A kind of bike", "A cloud shape", "The water cycle"], 2],
  ["Dolbear's law", "DOLE-bairz law", "A rule for guessing the temperature from how fast crickets chirp.", "c", "What does Dolbear's law use to estimate temperature?", ["Cricket chirps", "Bird feathers", "Cloud colors"], 0],
  ["pressure gradient", "PRESH-er GRAY-dee-unt", "The change in air pressure from one place to another that makes wind blow.", "h", "What does a pressure gradient make?", ["Snow", "Wind", "Earthquakes"], 1],
  ["radiative cooling", "RAY-dee-uh-tiv KOO-ling", "When heat escapes into space on clear, still nights, making it very cold.", "c", "What happens during radiative cooling?", ["Rain falls upward", "The Sun gets closer", "Heat escapes to space"], 2]
 ]},
 rocks:{jobs:["Junior Geologist", "Geologist", "Chief Geologist"],words:[
  ["crystallization", "kris-tuh-luh-ZAY-shun", "When minerals slowly build neat, repeating shapes called crystals, like inside a geode.", "m", "What forms during crystallization?", ["Crystals", "Clouds", "Bubbles"], 0],
  ["igneous", "IG-nee-us", "Rock made when hot melted rock, like lava, cools and hardens.", "m", "How does igneous rock form?", ["Sand gets glued", "Melted rock cools", "Shells pile up"], 1],
  ["sodium chloride", "SOH-dee-um KLOR-ide", "The chemical name for salt, the mineral halite.", "m", "What is sodium chloride?", ["Sugar", "Sand", "Salt"], 2],
  ["vesicles", "VES-ih-kulz", "Tiny holes left by gas bubbles in volcanic rock like pumice.", "h", "What made the vesicles in pumice?", ["Gas bubbles", "Tiny worms", "Raindrops"], 0],
  ["Mohs scale", "MOHZ skayl", "A scale from 1 to 10 for mineral hardness; diamond is a 10.", "m", "On the Mohs scale, what number is diamond?", ["1", "10", "5"], 1],
  ["allotrope", "AL-uh-trope", "A different form of the same element, like diamond and graphite from carbon.", "c", "Diamond and graphite are allotropes of which element?", ["Gold", "Iron", "Carbon"], 2],
  ["lodestone", "LOHD-stohn", "A naturally magnetic piece of the mineral magnetite.", "h", "What is special about a lodestone?", ["It is magnetic", "It glows", "It floats"], 0],
  ["plate tectonics", "playt tek-TON-iks", "Earth's giant rock plates slowly moving and pushing up mountains like Everest.", "m", "What do plate tectonics slowly move?", ["Clouds", "Earth's giant rock plates", "Ocean fish"], 1],
  ["inclusion", "in-KLOO-zhun", "Something trapped inside a mineral or amber, like an ancient insect.", "h", "What is an inclusion in amber?", ["A crack outside", "Its bright color", "Something trapped inside"], 2],
  ["downcutting", "DOWN-kut-ing", "When a river slowly wears its bed deeper and deeper into the rock, like the Colorado River in the Grand Canyon.", "h", "What did the Colorado River's downcutting do to the Grand Canyon?", ["Made it deeper", "Filled it with sand", "Froze it"], 0],
  ["metamorphic", "met-uh-MOR-fik", "Rock that was changed by great heat and pressure deep underground, like marble.", "m", "How does metamorphic rock form?", ["Lava cools quickly", "Heat and pressure change old rock", "Wind blows sand away"], 1],
  ["geothermal", "jee-oh-THUR-mul", "Heat that comes from deep inside the Earth.", "m", "Where does geothermal heat come from?", ["The Moon", "Ocean waves", "Inside the Earth"], 2]
 ]},
 cars:{jobs:["Junior Auto Engineer", "Automotive Engineer", "Chief Automotive Engineer"],words:[
  ["horsepower", "HORS-pow-er", "A unit of engine power. James Watt named it by comparing engines to strong horses.", "m", "What does horsepower measure?", ["Tire size", "Engine power", "Road length"], 1],
  ["lithium-ion battery", "LITH-ee-um EYE-on BAT-er-ee", "The rechargeable battery type that powers most electric cars.", "h", "What does a lithium-ion battery do in a car?", ["Stores power", "Holds gasoline", "Cleans windows"], 0],
  ["conspicuity", "kon-spih-KYOO-ih-tee", "How easy something is to notice, like a bright yellow school bus.", "c", "A bus with high conspicuity is easy to do what?", ["Lift up", "Drive slowly", "See"], 2],
  ["hydraulics", "hy-DRAW-liks", "Using pushed liquid to move heavy things, like raising a fire truck ladder.", "h", "What does hydraulics use to move heavy things?", ["Pushed liquid", "Magnets", "Wind"], 0],
  ["aerodynamics", "air-oh-dy-NAM-iks", "How air flows around moving things; race cars are shaped to slice through it.", "h", "Aerodynamics studies how what flows around a car?", ["Oil", "Air", "Paint"], 1],
  ["traction", "TRAK-shun", "The grip between a tire and the ground that keeps it from slipping.", "m", "What does traction help tires do?", ["Change color", "Make music", "Grip the ground"], 2],
  ["right-of-way", "ryt-uv-WAY", "The right to go first on a road. Traffic lights show which cars have it.", "h", "At a traffic light, which cars have the right-of-way?", ["Cars with a green light", "Cars with a red light", "The slowest cars"], 0],
  ["right-hand traffic", "RYT-hand TRAF-ik", "The rule of driving on the right side of the road, like in the US.", "h", "In right-hand traffic, which side do cars drive on?", ["Left", "Right", "Middle"], 1],
  ["mass production", "mas pruh-DUK-shun", "Making lots of the same thing quickly, like Ford's Model T cars.", "m", "What is mass production?", ["Fixing one old car", "Painting by hand", "Making many things fast"], 2],
  ["regenerative braking", "rih-JEN-er-uh-tiv BRAY-king", "Using a car's slowing down to make electricity for its battery.", "h", "What does regenerative braking make?", ["Electricity", "Smoke", "Rain"], 0],
  ["combustion", "kum-BUS-chun", "Burning fuel to release energy, which pushes an engine's pistons.", "m", "What happens during combustion?", ["Water freezes", "Fuel burns", "Paint dries"], 1],
  ["supersonic", "soo-per-SON-ik", "Faster than the speed of sound, like the Thrust SSC car.", "m", "What does supersonic mean?", ["Very quiet", "Very tiny", "Faster than sound"], 2]
 ]},
 trains:{jobs:["Junior Transport Engineer", "Transportation Engineer", "Chief Transport Engineer"],words:[
  ["buoyancy", "BOY-un-see", "The upward push that lets things float, like a hot air balloon.", "m", "What does buoyancy help a balloon do?", ["Float up", "Sink down", "Spin around"], 0],
  ["locomotive", "loh-kuh-MOH-tiv", "The engine car that pulls or pushes a train.", "m", "What does a locomotive do?", ["Sells tickets", "Pulls the train", "Carries only mail"], 1],
  ["rotor", "ROH-ter", "The spinning blades on a helicopter that lift it into the air.", "m", "What does a helicopter's rotor do?", ["Holds fuel", "Plays music", "Spins to lift it"], 2],
  ["cruising altitude", "KROO-zing AL-tih-tood", "The height where a jet flies for most of its trip.", "m", "What is a jet's cruising altitude?", ["Its main flying height", "Its top speed", "Its number of seats"], 0],
  ["aeronautics", "air-uh-NAW-tiks", "The science of building and flying aircraft, like the Wright brothers' first airplane.", "h", "What does aeronautics study?", ["Undersea caves", "Aircraft and flight", "Train tracks"], 1],
  ["pantograph", "PAN-tuh-graf", "The arm on an electric train's roof that takes power from overhead wires.", "h", "What does a train's pantograph collect?", ["Rainwater", "Tickets", "Electricity"], 2],
  ["displacement", "dis-PLAYS-munt", "The weight of water a ship pushes aside as it floats. It equals the ship's own weight.", "h", "What does a ship's displacement measure?", ["Water pushed aside", "Its speed", "Its paint color"], 0],
  ["magnetic levitation", "mag-NET-ik lev-ih-TAY-shun", "Using magnets to lift something so it floats, like a maglev train.", "h", "What does magnetic levitation use to lift a train?", ["Wind", "Magnets", "Wheels"], 1],
  ["ballast tank", "BAL-ust tank", "A tank a submarine fills with water to sink, or air to rise.", "h", "What goes into a ballast tank to make a sub sink?", ["Air", "Sand", "Water"], 2],
  ["tacking", "TAK-ing", "Zigzagging a sailboat back and forth to travel toward the wind.", "m", "What is tacking?", ["Zigzagging into the wind", "Dropping the anchor", "Painting the sail"], 0],
  ["fuselage", "FYOO-suh-lahzh", "The long main body of an airplane, where passengers sit.", "h", "What is an airplane's fuselage?", ["The wing tip", "Its main body", "The engine fan"], 1],
  ["rail gauge", "RAYL gayj", "The distance between the two rails of a track; Russia uses an extra-wide gauge.", "h", "What does rail gauge measure?", ["Train speed", "Number of cars", "Space between rails"], 2]
 ]},
 robots:{jobs:["Robotics Technician", "Robotics Engineer", "Chief Robotics Engineer"],words:[
  ["infrared", "IN-fruh-red", "Light our eyes can't see. Robot vacuums use it to spot walls and stairs.", "m", "What is infrared?", ["Light we cannot see", "A loud beeping sound", "A kind of wheel"], 0],
  ["gear ratio", "GEER RAY-shee-oh", "How many times one gear turns compared to the gear it fits with.", "m", "What does a gear ratio compare?", ["The colors of gears", "How two gears turn", "How heavy gears are"], 1],
  ["mechanical advantage", "meh-KAN-ih-kul ad-VAN-tij", "How much a machine multiplies your push or pull, making work easier.", "m", "What does mechanical advantage tell you?", ["How old a machine is", "What a machine is named", "How much force is multiplied"], 2],
  ["end effector", "END ee-FEK-ter", "The tool at the tip of a robot arm, like a welder or gripper.", "c", "Where is a robot's end effector?", ["At its arm tip", "Inside its battery", "Under its wheels"], 0],
  ["neologism", "nee-OL-uh-jiz-um", "A brand-new word. Robot was a new word in a Czech play from 1920.", "h", "What is a neologism?", ["A very old book", "A brand-new word", "A robot's battery"], 1],
  ["computer vision", "kum-PYOO-ter VIZH-un", "How computers use cameras to understand what they are seeing.", "h", "What does computer vision help a robot do?", ["Charge its battery", "Talk more loudly", "Understand camera pictures"], 2],
  ["vacuum tube", "VAK-yoom TOOB", "A glowing glass tube that worked as a switch inside the first computers.", "h", "What job did vacuum tubes do in early computers?", ["Worked as switches", "Cleaned the floors", "Kept the room cool"], 0],
  ["autonomous", "aw-TON-uh-mus", "Able to act on its own, without a person controlling every move.", "h", "What can an autonomous robot do?", ["Only move when pushed", "Move on its own", "Never move at all"], 1],
  ["remotely operated vehicle", "rih-MOHT-lee OP-uh-ray-tid VEE-ih-kul", "An underwater robot steered by people on a ship, joined to it by a long cable.", "h", "Who steers a remotely operated vehicle?", ["The ocean waves", "A fish", "People on a ship"], 2],
  ["rotorcraft", "ROH-ter-kraft", "An aircraft that flies using spinning blades, like a helicopter. Ingenuity was a rotorcraft.", "h", "Which is a rotorcraft?", ["A helicopter", "A hot air balloon", "A paper airplane"], 0],
  ["automaton", "aw-TOM-uh-ton", "An old-time machine built to move by itself, like the ones Hero made.", "h", "What is an automaton?", ["A kind of Greek food", "A machine that moves itself", "A very old coin"], 1],
  ["interstellar space", "in-ter-STEL-er SPAYSS", "The space between the stars. Voyager 1 is traveling there now.", "m", "Interstellar space is the space between what?", ["Oceans", "Cities", "Stars"], 2]
 ]},
 sports:{jobs:["Assistant Coach", "Sports Scientist", "Head Coach"],words:[
  ["association football", "uh-soh-see-AY-shun FOOT-bawl", "Soccer's official name. The word soccer comes from association.", "h", "Association football is another name for what?", ["Basketball", "Soccer", "Tennis"], 1],
  ["regulation", "reg-yoo-LAY-shun", "An official rule. A regulation hoop is 10 feet high, like the first baskets.", "m", "What does regulation mean in sports?", ["A kind of ball", "A team snack", "An official rule"], 2],
  ["turbulence", "TER-byoo-lents", "Swirly, mixed-up air. Dimples make a thin layer of it so balls fly farther.", "h", "What is turbulence?", ["Swirly, mixed-up air", "A kind of golf club", "A type of grass"], 0],
  ["elasticity", "ee-las-TIS-ih-tee", "How much something stretches or bounces back. Cold rubber pucks have less of it.", "h", "Something with lots of elasticity will do what?", ["Melt right away", "Bounce or stretch back", "Glow in the dark"], 1],
  ["prolate spheroid", "PROH-layt SFEER-oyd", "A stretched-out ball shape, a lot like a football.", "c", "What shape is a prolate spheroid?", ["A flat square", "A triangle", "A stretched-out ball"], 2],
  ["Magnus effect", "MAG-nus ee-FEKT", "When a spinning ball curves because its spin pushes air to one side.", "h", "The Magnus effect makes a spinning ball do what?", ["Curve through the air", "Get heavier", "Change color"], 0],
  ["contrast", "KON-trast", "How much something stands out from what is behind it, like yellow balls.", "m", "High contrast makes things what?", ["Harder to hear", "Easier to see", "Heavier to lift"], 1],
  ["aerobic", "air-OH-bik", "Using oxygen to make energy for long, steady exercise, like running a marathon.", "h", "Aerobic exercise uses what to make energy?", ["Moonlight", "Loud music", "Oxygen"], 2],
  ["gilding", "GIL-ding", "Covering something with a very thin layer of gold, like Olympic gold medals.", "h", "What is gilding?", ["Covering with thin gold", "Melting ice", "Painting with blue"], 0],
  ["cubic meter", "KYOO-bik MEE-ter", "A box of space 1 meter on each side. An Olympic pool holds about 2,500.", "m", "What does a cubic meter measure?", ["How hot it is", "How much space", "How loud it is"], 1],
  ["volley", "VOL-ee", "To hit a ball before it touches the ground. Volleyball, invented in 1895, is named for it.", "m", "What does it mean to volley a ball?", ["Kick it into a goal", "Roll it on the floor", "Hit it before it lands"], 2],
  ["pentathlon", "pen-TATH-lon", "A contest with five events. Ancient Greek athletes competed in one.", "m", "How many events are in a pentathlon?", ["Five", "Two", "Ten"], 0]
 ]},
 music:{jobs:["Session Musician", "Composer", "Orchestra Conductor"],words:[
  ["octave", "OK-tiv", "The jump from one note to the next with the same name, like C to C.", "m", "An octave goes from one C to what?", ["The letter Z", "A drum beat", "The next C"], 2],
  ["fret", "FRET", "A thin metal bar on a guitar's neck. Pressing near one changes the note.", "m", "What do guitar frets help you do?", ["Play different notes", "Tune a drum", "Hold the strap"], 0],
  ["frequency", "FREE-kwen-see", "How many times something shakes each second. Faster shaking makes a higher sound.", "m", "A higher frequency makes what kind of sound?", ["A quieter drum", "A higher sound", "No sound at all"], 1],
  ["rosin", "RAH-zin", "A hard, sticky stuff made from tree sap, rubbed on bow hair so it grips the strings.", "m", "Why do violin players rub rosin on the bow?", ["To make it shiny", "To make it lighter", "So it grips the strings"], 2],
  ["embouchure", "AHM-boo-shoor", "The way a player shapes their lips and mouth to play an instrument.", "h", "What is a trumpet player's embouchure?", ["How they shape their lips", "The case they carry", "The songs they know"], 0],
  ["timbre", "TAM-ber", "The special sound quality that makes a violin and a flute sound different.", "h", "What does timbre describe?", ["How loud music is", "An instrument's special sound", "How long a song is"], 1],
  ["glissando", "glih-SAHN-doh", "Sliding quickly across many notes, like sweeping fingers along harp strings.", "h", "What is a glissando?", ["Playing one note softly", "Stopping the music", "Sliding across many notes"], 2],
  ["minuet", "min-yoo-ET", "A graceful dance tune with 3 beats in each measure. Some of Mozart's first pieces were minuets.", "h", "How many beats are in each measure of a minuet?", ["3", "5", "7"], 0],
  ["ligature", "LIG-uh-cher", "The clamp that holds the reed onto a saxophone's mouthpiece.", "h", "What does a ligature hold on a saxophone?", ["The music stand", "The reed", "The case"], 1],
  ["symphony", "SIM-fuh-nee", "A big piece of music for a full orchestra. Beethoven wrote nine.", "m", "Who plays a symphony?", ["One drummer", "A school choir only", "A full orchestra"], 2],
  ["medium", "MEE-dee-um", "The material sound travels through, like air or water.", "m", "In science, what is a medium for sound?", ["What sound travels through", "A middle-sized drum", "A kind of song"], 0],
  ["manual", "MAN-yoo-ul", "On an organ, a keyboard played with the hands. The Atlantic City organ has 7.", "h", "On a pipe organ, what is a manual?", ["A foot pedal", "A keyboard for hands", "A kind of pipe"], 1]
 ]},
 art:{jobs:["Studio Artist", "Art Curator", "Chief Curator"],words:[
  ["subtractive mixing", "sub-TRAK-tiv MIK-sing", "Mixing paints. Each paint soaks up some light, so mixed colors get darker.", "h", "In subtractive mixing, what do paints do to light?", ["Soak some of it up", "Make it louder", "Turn it into water"], 0],
  ["pigment", "PIG-ment", "A colored powder that gives crayons and paints their color.", "m", "What does a pigment give a crayon?", ["Its smell", "Its color", "Its box"], 1],
  ["graphite", "GRAF-ite", "The soft gray material inside pencils that makes the marks.", "m", "Where would you find graphite?", ["Inside a crayon box", "Inside bread", "Inside a pencil"], 2],
  ["analogous colors", "uh-NAL-uh-gus KUL-erz", "Colors that sit right next to each other on the color wheel.", "h", "Where are analogous colors on the color wheel?", ["Right next to each other", "Straight across", "Not on the wheel"], 0],
  ["sfumato", "sfoo-MAH-toh", "Soft, smoky blending with no sharp lines, used in the Mona Lisa.", "c", "What does sfumato look like?", ["Bright, sharp lines", "Soft, smoky blending", "Tiny dots of color"], 1],
  ["still life", "STIL LYFE", "A painting of things that do not move, like flowers in a vase.", "m", "What does a still life show?", ["Running animals", "Moving cars", "Objects that do not move"], 2],
  ["patina", "puh-TEE-nuh", "A thin layer, often green, that forms on copper over time.", "h", "What is the green layer on old copper called?", ["Patina", "Pigment", "Pencil"], 0],
  ["ochre", "OH-ker", "A natural red or yellow earth color used in cave paintings.", "h", "What is ochre?", ["A type of cave", "A natural earth color", "A stone tool"], 1],
  ["moai", "MOH-eye", "The name for the giant stone statues on Easter Island.", "c", "What are moai?", ["A kind of paintbrush", "Big ocean waves", "Easter Island stone statues"], 2],
  ["pointillism", "POYN-tuh-liz-um", "A way of painting with many tiny dots of color, like Seurat did.", "h", "What is pointillism painting made of?", ["Tiny dots of color", "Long brush strokes", "Torn paper"], 0],
  ["fresco", "FRES-koh", "Painting on wet plaster so the colors dry right into the wall or ceiling.", "h", "What do fresco painters paint on?", ["Paper bags", "Wet plaster", "Glass bottles"], 1],
  ["lapis lazuli", "LAP-is LAZ-yoo-lee", "A deep blue stone that was ground up to make ultramarine paint.", "h", "What is lapis lazuli?", ["A green leaf", "A kind of brush", "A deep blue stone"], 2]
 ]},
 food:{jobs:["Line Cook", "Sous Chef", "Executive Chef"],words:[
  ["pericarp", "PAIR-ih-karp", "The tough outer shell of a popcorn kernel that traps steam until it bursts.", "c", "What does a popcorn kernel's pericarp do?", ["Makes the corn yellow", "Traps the steam inside", "Adds the salt"], 1],
  ["density", "DEN-sih-tee", "How tightly stuff is packed into a space. Less dense things float.", "m", "An apple floats because it has lower what?", ["Color", "Sweetness", "Density"], 2],
  ["fermentation", "fer-men-TAY-shun", "When tiny living things like yeast eat sugar and make gas and other things.", "h", "In bread, what does fermentation make?", ["Gas bubbles", "Ice crystals", "Salt"], 0],
  ["Theobroma", "thee-oh-BROH-muh", "The science name of the cacao tree. It means food of the gods.", "c", "Theobroma is the science name for which tree?", ["The apple tree", "The cacao tree", "The pine tree"], 1],
  ["ovary", "OH-vuh-ree", "The part of a flower that swells into a fruit with seeds inside.", "h", "What does a flower's ovary grow into?", ["A leaf", "A root", "A fruit"], 2],
  ["anthocyanin", "an-thoh-SY-uh-nin", "A natural color that makes purple carrots, blueberries, and grapes purple.", "c", "What does anthocyanin give some carrots?", ["A purple color", "A salty taste", "A crunchy sound"], 0],
  ["nitrogen fixation", "NY-truh-jen fik-SAY-shun", "How legumes, with help from tiny bacteria, turn nitrogen from air into plant food.", "h", "What does nitrogen fixation make for plants?", ["Colder water", "Plant food from air", "Sweeter peanuts"], 1],
  ["denature", "dee-NAY-cher", "When heat changes a protein's shape, like when egg whites cook.", "h", "What happens when heat denatures a protein?", ["It turns into sugar", "It starts to glow", "Its shape changes"], 2],
  ["carbon dioxide", "KAR-bun dy-OK-side", "A gas that the cheese bacteria make. Its bubbles form the holes.", "m", "What makes the holes in Swiss cheese?", ["Carbon dioxide bubbles", "Tiny mice", "Drops of milk"], 0],
  ["freezing point depression", "FREE-zing POYNT dee-PRESH-un", "Salt makes water freeze at a colder temperature, so salty ice gets colder.", "h", "With salt, water freezes at what kind of temperature?", ["A hotter temperature", "A colder temperature", "It never freezes"], 1],
  ["Scoville scale", "SKOH-vil SKAYL", "A scale that measures how spicy hot a pepper is.", "h", "What does the Scoville scale measure?", ["How heavy a pepper is", "How long a pepper is", "How spicy a pepper is"], 2],
  ["hygroscopic", "hy-groh-SKOP-ik", "Pulls in water. Honey pulls water out of germs, so they cannot grow.", "c", "What does a hygroscopic food like honey do?", ["Pulls in water", "Glows in the dark", "Makes loud pops"], 0]
 ]}
};
