// Bank version 2: vocabulary for Grades 3–5. 7th field = grade.
pack({
vocab:[
 ["shallow", "not deep", "Near the edge of the pond, the water is ___, so it only comes up to your ankles.", null, "deep", "🐸", 3],
 ["glisten", "to shine with a wet sparkle", "Drops of dew ___ like glitter on the grass in the morning sun.", "sparkle", null, "✨", 3],
 ["flexible", "able to bend easily without breaking", "A ___ willow branch bends in the wind but does not snap.", null, "stiff", "🌿", 3],
 ["identify", "to figure out what something is", "Use the chart to ___ which kind of leaf you found.", "recognize", null, "🍃", 3],
 ["discover", "to find something for the first time", "Explorers hoped to ___ an island no one had seen before.", "uncover", null, "🗺️", 3],
 ["pounce", "to jump on something suddenly to catch it", "The cat crouched low, ready to ___ on the mouse.", "leap", null, "🐈", 3],
 ["decay", "to rot and slowly break down", "Fallen leaves ___ and turn into rich soil.", "rot", null, "🍂", 3],
 ["sprout", "to start to grow", "Bean seeds ___ tiny green shoots a few days after you plant them.", "grow", null, "🌱", 3],
 ["wilt", "to droop because of not enough water", "Flowers ___ and hang their heads when nobody waters them.", "droop", null, "🥀", 3],
 ["fertile", "good for growing lots of plants", "The ___ valley grows so many crops that it feeds the whole town.", null, "barren", "🌽", 3],
 ["drift", "to be carried slowly by wind or water", "Without an oar, our raft began to ___ down the river.", "float", null, "🌊", 3],
 ["slippery", "so smooth or wet that things slide", "The wet rocks were so ___ that my feet slid right out from under me.", "slick", null, "🧊", 3],
 ["hollow", "empty inside", "The owl made its nest inside a ___ log.", "empty", "solid", "🦉", 3],
 ["pattern", "shapes or colors that repeat in order", "The snake's scales make a diamond ___ that repeats down its back.", "design", null, "🐍", 3],
 ["imitate", "to copy what someone else does or says", "Parrots can ___ the sounds that people make.", "copy", null, "🦜", 3],
 ["protect", "to keep safe from harm", "A turtle's hard shell helps ___ its soft body.", "guard", null, "🛡️", 3],
 ["capture", "to catch and hold", "Spiders spin sticky webs to ___ insects.", "catch", "release", "🕸️", 3],
 ["chilly", "a little bit cold", "Bring a jacket, because the mountain air is ___.", "cool", "warm", "🧥", 3],
 ["scorching", "very, very hot", "It was so ___ that the sidewalk felt like a frying pan.", null, "freezing", "🔥", 3],
 ["boulder", "a very large rock", "A huge ___ rolled down the mountain and blocked the road.", "stone", null, "⛰️", 3],
 ["vanish", "to disappear suddenly", "Stars seem to ___ when the sun rises.", "disappear", null, "🌠", 3],
 ["cling", "to hold on tightly", "Baby koalas ___ to their mother's back.", "grip", null, "🐨", 3],
 ["dart", "to move suddenly and quickly", "The lizard will ___ under a rock the moment it sees you.", "dash", null, "🦎", 3],
 ["route", "the path you take to get somewhere", "Which ___ should we take to reach the top of the hill?", "path", null, "🧭", 3],
 ["tangle", "to twist together into a messy knot", "If you do not wind the kite string carefully, it will ___.", "twist", null, "🧶", 3],
 ["edible", "safe to eat", "Some mushrooms are ___, but others are poisonous.", null, "poisonous", "🍄", 3],
 ["prickly", "covered with sharp points", "A porcupine's ___ quills keep predators away.", "spiky", "smooth", "🦔", 3],
 ["gnaw", "to keep chewing on something hard", "Beavers ___ through tree trunks with their sharp teeth.", "chew", null, "🦷", 3],
 ["ripe", "ready to be picked and eaten", "The banana is yellow now, so it is ___.", "ready", null, "🍌", 3],
 ["fragrant", "having a sweet, nice smell", "The ___ roses filled the garden with a sweet smell.", "scented", "stinky", "🌹", 3],
 ["steep", "going up or down sharply", "The trail was so ___ that we had to climb using our hands.", null, null, "🥾", 3],
 ["plunge", "to drop down fast into water", "The pelican will ___ into the sea to catch a fish.", "drop", null, "🐟", 3],
 ["whirl", "to spin around and around fast", "The wind made the fallen leaves ___ around and around like a tiny tornado.", "spin", null, "🌪️", 3],
 ["roam", "to wander around with no plan", "Our dog loves to ___ around the yard, sniffing everything.", null, null, "🐕", 3],
 ["dangerous", "likely to hurt you", "Touching a jellyfish is ___ because it can sting you.", "risky", "safe", "⚠️", 3],
 ["repair", "to fix something that is broken", "Beavers ___ holes in their dam with fresh mud.", "fix", null, "🔧", 3],
 ["speckled", "covered with tiny spots", "A ___ trout has tiny dots all over its skin.", "spotted", null, "🎣", 3],
 ["flutter", "to flap wings quickly and lightly", "Butterflies ___ their wings gently as they sip nectar.", "flap", null, "🦋", 3],
 ["bumpy", "covered with bumps; not smooth", "The ___ dirt road made our bus bounce.", "rough", "smooth", "🚌", 3],
 ["weary", "very tired", "The ___ geese rested on the lake after flying all day.", "tired", null, "😴", 3],
 ["ripple", "a small wave on water", "Tossing a pebble into the pond made a ___.", "wave", null, "💧", 3],
 ["sway", "to move slowly from side to side", "Tall palm trees ___ in the ocean breeze.", "swing", null, "🌴", 3],
 ["adapt", "to change to fit a new place or situation", "Arctic foxes ___ to winter by growing thick white fur.", "adjust", null, "🦊", 4],
 ["evidence", "facts or clues that show something is true", "Muddy footprints were ___ that a deer had walked by.", "proof", null, "🐾", 4],
 ["estimate", "to make a careful guess about an amount", "Let's ___ how many birds are in the flock without counting them all.", "guess", null, "🦆", 4],
 ["conserve", "to use carefully so it does not run out", "Turn off the tap while brushing to ___ water.", null, "waste", "🚰", 4],
 ["native", "living or growing naturally in a place", "Kangaroos are ___ to Australia.", null, "foreign", "🦘", 4],
 ["thrive", "to grow strong and healthy", "Coral reefs ___ in warm, clean water.", null, "wither", "🐠", 4],
 ["accurate", "correct, with no mistakes", "A good scale gives an ___ weight.", "correct", "wrong", "⚖️", 4],
 ["detect", "to notice something that is hard to see or hear", "Bats use echoes to ___ insects in the dark.", "sense", null, "📡", 4],
 ["source", "where something comes from", "The Sun is Earth's main ___ of light and heat.", "origin", null, "☀️", 4],
 ["vary", "to be different from one another", "Leaf shapes ___ from one kind of tree to another.", "differ", null, "🍁", 4],
 ["illuminate", "to light up", "Fireflies ___ the dark field at night.", "light up", "darken", "🔦", 4],
 ["transform", "to change completely into something else", "A tadpole will ___ into a frog.", "convert", null, "🐛", 4],
 ["fragment", "a small piece broken off something", "The scientist found a sharp ___ of an old clay pot.", "piece", null, "🏺", 4],
 ["vertical", "straight up and down", "Draw a ___ line from the top of the page to the bottom.", "upright", "horizontal", "📏", 4],
 ["region", "an area or part of a place", "Which ___ of the country gets the most snow?", "area", null, "🗾", 4],
 ["seldom", "hardly ever", "Rain ___ falls in the desert.", null, "often", "🌵", 4],
 ["cease", "to stop", "The loud thunder will ___ when the storm passes.", "stop", "start", "🛑", 4],
 ["emerge", "to come out from inside or from hiding", "The butterfly will ___ from its chrysalis.", "appear", null, "🐣", 4],
 ["dwell", "to live in a place", "Some owls ___ in holes in cactus plants.", "live", null, "🦉", 4],
 ["obstacle", "something that blocks your way", "The fallen tree was an ___ on the trail.", "barrier", null, "🚧", 4],
 ["severe", "very bad or serious", "The doctor said the sunburn was ___ and needed care.", "harsh", null, "🥵", 4],
 ["attract", "to pull something closer", "A magnet will ___ paper clips.", null, "repel", "🧲", 4],
 ["expand", "to get bigger", "A balloon will ___ as you blow air into it.", "grow", "shrink", "🎈", 4],
 ["sequence", "the order that things happen in", "Put the frog life cycle pictures in the right ___.", "order", null, "🔢", 4],
 ["reduce", "to make smaller or less", "Using cloth bags can ___ the amount of trash we make.", "decrease", "increase", "♻️", 4],
 ["rotate", "to turn around a center point", "Earth takes one day to ___ once on its axis.", "spin", null, "🌍", 4],
 ["consume", "to eat or use up", "Caterpillars ___ lots of leaves every day.", "eat", "produce", "🥬", 4],
 ["visible", "able to be seen", "The comet was ___ without a telescope.", null, "invisible", "☄️", 4],
 ["summit", "the very top of a mountain", "The climbers reached the ___ of the mountain at sunrise.", "peak", "base", "🏔️", 4],
 ["permanent", "lasting forever or for a very long time", "Pen ink is ___, so it will not erase like pencil.", "lasting", "temporary", "🖊️", 4],
 ["hypothesis", "a guess you can test with an experiment", "My ___ is that plants will grow faster with more light.", "guess", null, "🧪", 5],
 ["dormant", "alive but resting and not active", "Seeds stay ___ in the cold ground until spring.", "inactive", "active", "🌰", 5],
 ["diverse", "made of many different kinds", "The rainforest is home to a ___ mix of plants and animals.", "varied", null, "🌺", 5],
 ["elevation", "how high a place is above the sea", "Few trees grow at a high ___ on a mountain.", "height", null, "🗻", 5],
 ["extract", "to pull or take something out", "Machines ___ oil from deep underground.", "remove", "insert", "🛢️", 5],
 ["contaminate", "to make dirty or unsafe with something harmful", "An oil spill can ___ ocean water.", "pollute", "purify", "☣️", 5],
 ["generate", "to make or produce", "Wind turbines ___ electricity.", "produce", null, "💨", 5],
 ["cultivate", "to grow crops or plants with care", "Farmers ___ rice in wet, flooded fields.", "grow", null, "🌾", 5],
 ["remote", "far away from towns and people", "The research camp was in a ___ part of Antarctica.", "distant", "nearby", "🏕️", 5],
 ["sufficient", "as much as you need; enough", "Is there ___ water for the whole hike?", "enough", null, "🥤", 5],
 ["vital", "needed to stay alive; a must-have", "Water is ___ for all living things.", "essential", null, "💧", 5],
 ["interior", "the inside part of something", "The ___ of the geode is full of sparkling crystals.", "inside", "outside", "💎", 5],
 ["classify", "to sort things into groups by how they are alike", "Scientists ___ animals into groups like mammals and birds.", "sort", null, "🗂️", 5],
 ["trait", "a feature passed from parents to their young", "Long ears are a ___ that rabbits get from their parents.", "feature", null, "🐇", 5],
 ["organism", "any living thing", "Every living ___ needs food and water.", "creature", null, "🦠", 5],
 ["microscopic", "too small to see without a microscope", "Germs are ___, so you need a microscope to see them.", null, "giant", "🧫", 5],
 ["moderate", "not too much and not too little", "Walk at a ___ pace, not too fast and not too slow.", "medium", "extreme", "🌡️", 5],
 ["obtain", "to get something", "You must ___ a permit before camping in the park.", "get", null, "🎫", 5],
 ["resilient", "able to bounce back after something bad", "The ___ forest grew back quickly after the fire.", null, "fragile", "💪", 5],
 ["benefit", "to help", "Bees ___ farmers by pollinating their crops.", "help", "harm", "🐝", 5],
 ["function", "the job something does", "The main ___ of a bird's beak is to help it eat.", "purpose", null, "⚙️", 5],
 ["mature", "fully grown", "It takes about 20 years for an oak to become ___ and make acorns.", "adult", "young", "🌳", 5],
 ["approximately", "about; close to but not exact", "The biggest blue whales are ___ 100 feet long.", "about", "exactly", "🐳", 5],
 ["significant", "big enough to notice or to matter", "Planting 1,000 trees made a ___ difference, and the city's air got much cleaner.", "major", "minor", "📈", 5],
 ["verify", "to check that something is true", "Call the museum to ___ that it is open today.", "confirm", null, "✅", 5],
 ["consequence", "something that happens because of an action", "Dirty air is one ___ of burning too much fuel.", "result", "cause", "🏭", 5],
 ["temporary", "lasting only a short time", "The rainbow was ___ and faded in just a few minutes.", "brief", "permanent", "🌈", 5],
 ["navigate", "to find your way from place to place", "Sailors used the stars to ___ their ships at night.", "steer", null, "⛵", 5],
 ["emit", "to give off light, heat, sound or gas", "Volcanoes ___ gas and ash into the air.", null, "absorb", "🌋", 5],
 ["compress", "to squeeze into a smaller space", "Push down hard on the trash to ___ it so more fits in the can.", "squeeze", null, "🗜️", 5]
]
});
